### ISSUE TITLE
Initial checklist

### ISSUE THREAD

**Issue by mateomh** [jurgen1c/Design-Teardown#1]
# Checklist for the configuration and tracking of the project

## Before starting to code
- [x] Coding partner set as collaborator.
- [x] Folder .github/worflows and linters.yml ready. [Microverse guidelines](https://github.com/microverseinc/linters-config)
- [x] .gitignore files created with the respective files.
- [x] Setup the linters locally to your project. [Microverse guidelines](https://github.com/microverseinc/linters-config)
- [x] Copy the .hintrc and the stylelintrc.json to the project root folder.
- [x] Create the feature branch for the project.
- [x] Create index.html in the root folder.
- [x] Create the css folder and styles.css file inside it.
- [x] Create the images folder for the project
- [x] Link the css files and other important links (fontawesome or googlefonts) and verify that they working properly
